-- 1. Creazione della tabella
CREATE TABLE IF NOT EXISTS players_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stagione TEXT,
    id_univoco_giocatore INTEGER,
    nome_giocatore TEXT,
    ruolo TEXT,
    squadra TEXT,
    abbreviazione_squadra TEXT,
    lega TEXT,
    overall INTEGER,
    potenziale INTEGER,
    valore_di_mercato TEXT,
    eta TEXT,
    nazionalita TEXT
);

-- 2. Creazione degli Indici per velocizzare le ricerche del gioco
CREATE INDEX IF NOT EXISTS idx_players_stagione ON players_history(stagione);
CREATE INDEX IF NOT EXISTS idx_players_id_giocatore ON players_history(id_univoco_giocatore);
CREATE INDEX IF NOT EXISTS idx_players_abbreviazione ON players_history(abbreviazione_squadra);
CREATE INDEX IF NOT EXISTS idx_players_lega ON players_history(lega);
